// vue-app/src/components/AddNinja.vue
<template>
  <div>
    <form @submit.prevent="handleSubmit">
      <label for="name"
        >Name: <input type="text" id="name" v-model="name"
      /></label>
      <label for="age">Age: <input type="text" id="age" v-model="age"/></label>
      <label for="belt"
        >Belt: <input type="text" id="belt" v-model="belt"
      /></label>
      <button>Submit</button>
    </form>
  </div>
</template>

<script>
export default {
  props: {
    addNinja: {
      type: Function
    }
  },
  data() {
    return {
      name: null,
      age: null,
      belt: null
    };
  },
  methods: {
    handleSubmit() {
      let newNinja = {
        name: this.name,
        age: this.age,
        belt: this.belt
      };
      this.addNinja(newNinja);
    }
  }
};
</script>

<style></style>

// svelte-app/src/components/AddNinja.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  let name = null;
  let age = null;
  let belt = null;
  
  function handleSubmit() {
    let newNinja = {
      name: name,
      age: age,
      belt: belt,
      id: Math.random()
    }

		dispatch('addNinja', newNinja);
	}
</script>

<form on:submit|preventDefault={handleSubmit}>
  <label for="name">Name: <input id="name" type="text" bind:value={name}></label>
  <label for="age">Age: <input id="age" type="text" bind:value={age}></label>
  <label for="bel">Belt: <input id="belt" type="text" bind:value={belt}></label>
  <button>Submit</button>
</form>
