// my-app/src/components/Ninjas.jsx
import React from "react";

const Ninjas = ({ ninjas, deleteNinja }) => {
  const renderList = ninjas.map((ninja) => {
    return ninja.age > 20 ? (
      <div key={ninja.id}>
        <h3>Name: {ninja.name}</h3>
        <p>Age: {ninja.age}</p>
        <p>Belt: {ninja.belt}</p>
        <button
          onClick={() => {
            deleteNinja(ninja.id);
          }}
        >
          Delete
        </button>
        <hr />
      </div>
    ) : null;
  });

  return <div className="ninja-list">{renderList}</div>;
};

export default Ninjas;

// svelte-app/src/components/Ninjas.svelte
<script>
  export let ninjas = []
  import { createEventDispatcher } from 'svelte';
  const dispatch = createEventDispatcher();

  function handleButton(id) {
    dispatch("deleteNinja", {id: id})
  }
</script>

<div class="ninja-list">
  {#each ninjas as ninja }
    {#if ninja.age > 20}
      <div class="ninja" id={ninja.id}>
        <h3>Name: {ninja.name}</h3>
        <p>Age: {ninja.age}</p>
        <p>Belt: {ninja.belt}</p>
        <button on:click={() => {handleButton(ninja.id)}}>Delete</button>
        <hr>
      </div>
    {/if}
  {/each}
</div>
